name: tnd-system
services:
    frontend:
        build: ./frontend
        # Add the relavant image name here
        image: iddhi/tnd-system:frontend-alpine-1.0.13
        ports:
            - "80:80"
        environment:
            - PORT=80
            - VITE_BACKEND_URL=http://localhost:3000
        stdin_open: true
        tty: true

    backend:
        build: ./backend
        # Add the relavant image name here
        image: iddhi/tnd-system:backend-alpine-1.0.13
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - JWT_PRIVATE_KEY=SecretKey
            - DB=mongodb://admin:password@database:27017/tnd_system
            - EMAIL=company_email
            - EMAIL_PASSWORD=company_email_password
        depends_on:
            - database
        networks:
            - database-driver
        stdin_open: true
        tty: true
        volumes:
            - upload_data:/usr/src/app/uploads
            - whatsapp_data:/usr/src/app/whatsapp_cache

    # database
    database:
        image: mongo:6.0.15-rc0-jammy
        ports:
            - "27017:27017"
        networks:
            - database-driver
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo_data:/data/db

networks:
    database-driver:
        driver: bridge

volumes:
    mongo_data:
    upload_data:
    whatsapp_data:
